baseURL: https://ma-paroisse.ch/
title: ma-paroisse.ch

languageCode: fr-ch
defaultContentLanguage: fr

canonifyURLs: true
copyright: Nicolas Friedli
disableFastRender: true
disableFastRender: true
# enableGitInfo: true
cleandestinationdir: true
removePathAccents: true

author:
  name: Nicolas Friedli
  email: nicolasfriedli@protonmail.ch

disableKinds:
  - taxonomy
  - term
  - 404

markup:
  goldmark:
    renderer:
      unsafe: true

params:
  footer: |
    **Site en développement!**  
    N'hésitez pas proposer des nouveautés ou des corrections.  
    **Contact:** nicolasfriedli@protonmail.ch  
    En savoir plus sur https://github.com/nfriedli/ma-paroisse.ch
  images:
    - https://cdn.pixabay.com/photo/2018/02/23/22/48/light-3176887_960_720.jpg
    - https://cdn.pixabay.com/photo/2015/12/08/00/27/church-1081718_960_720.jpg