baseURL: https://ma-paroisse.ch/
title: ma-paroisse.ch

languageCode: fr-ch
defaultContentLanguage: fr

canonifyURLs: true
copyright: CC0 (domaine public)
disableFastRender: true
# enableGitInfo: true
cleandestinationdir: true
removePathAccents: true

author:
  name: Nicolas Friedli
  email: nicolas.friedli+mp@gmail.com

disableKinds:
  - RSS
  - taxonomy
  - term
  - 404

markup:
  goldmark:
    renderer:
      unsafe: true

outputs:
  home:
    - html
    - json
  section:
    - html
    - json
  page:
    - html

params:
  footer: |  
    Contact: nicolas.friedli+mp@gmail.com  
    Licence: CC0 (domaine public)  

    [Plan complet](/sitemap/ "Toutes les paroisses sur une seule page") /
    [GitHub & en savoir plus](https://github.com/nfriedli/ma-paroisse.ch "README et sources du projet sur GitHub")  / 
    [Églises ouvertes](https://eglises-ouvertes.ch/ "Églises protestantes réformées accessibles à la visite en Suisse romande") /
    [Réseau protestant](https://reseau-protestant.ch/liste/ "Liste de sites protestants (réformés) de Suisse romande")
  images:
    - https://cdn.pixabay.com/photo/2018/02/23/22/48/light-3176887_960_720.jpg
    - https://cdn.pixabay.com/photo/2015/12/08/00/27/church-1081718_960_720.jpg