baseURL: https://ma-paroisse.netlify.app/
title: ma-paroisse.ch

languageCode: fr-ch
defaultContentLanguage: fr

canonifyURLs: true
copyright: Nicolas Friedli
disableFastRender: true
disableFastRender: true
enableGitInfo: true
cleandestinationdir: true
removePathAccents: true

author:
  name: Nicolas Friedli
  email: nicolasfriedli@protonmail.ch

disableKinds:
  - taxonomy
  - term
  - 404

markup:
  goldmark:
    renderer:
      unsafe: true

params:
  footer: |
    **Site en développement!**  
    N'hésitez pas à créer ou compléter des fiches paroissiales.  
    **Contact:** nicolasfriedli@protonmail.ch
  images:
    - https://cdn.pixabay.com/photo/2020/02/17/16/47/sherlock-4857024_960_720.jpg
  slogan: Trouver une paroisse protestante réformée en 5 secondes